name: gcc-arm

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
    - name: make clean
      run: make clean
      shell: cmd
    - name: make all
      run: make all
      shell: cmd
